M48
; DRILL file {KiCad 7.0.11-7.0.11~ubuntu20.04.1} date Thu Aug 15 12:33:14 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-08-15T12:33:14+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-7.0.11~ubuntu20.04.1
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.300
%
G90
G05
T1
X-1.119Y-15.755
X3.004Y-14.622
X3.006Y-15.64
M30
